plugins { id 'com.android.application' }
android {
    namespace 'com.salah.reminder'
    compileSdk 34
    defaultConfig {
        applicationId "com.salah.reminder"
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName "2.1"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        encoding = "UTF-8"
    }
}
